title: React Native For Web Developers
description: "React Native Tutorials for Web Developers"
author: Kevin Scott
language: en
timezone: UTC
url: https://reactnativeforwebdevelopers.com
root: /
permalink: :title/
code_dir: downloads/code
new_post_name: :title.md # File name of new posts
post_asset_folder: true
highlight:
  enable: true
  line_number: false
per_page: 0

theme: even
deploy:
  type: git
  repo: git@github.com:thekevinscott/reactnativeforwebdevelopers.git

google_analytics:
