# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2017

# Custom your favicon.ico in `site/source`
favicon: /favicon.ico

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: default

# ===========================================
# Menu Settings
# ===========================================
menu:
  Home: /
  #Archives: /archives/
  # Tags: /tags
  # Categories: /categories
  # About: /about

# ===========================================
# Theme Settings
# ===========================================
# theme styling
# color: Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
theme:
  color: Default
  toc: true
  search: false
  fancybox: false

reward:
  enable: true
  qrCode:
    wechat: /image/reward/wechat.png
    alipay: /image/reward/alipay.png

# ===========================================
# Social links Settings
# ===========================================
social:
  email: your@email.com
  stack-overflow:
  twitter:
  facebook:
  linkedin:
  google:
  github:
  weibo:
  zhihu:
  pocket:

# ===========================================
# Third Party Services Settings
# ===========================================

# Google Analytics
google_analytics:

# ===========================================
# Version
# ===========================================
version: 0.1.2
